### ISSUE TITLE
DOI for citing

### ISSUE THREAD

**Issue by lazappi** [arnavm/multimodal-scRNA-seq#1]
Thanks for putting this image together! I think it's great and I'm going to put it in my thesis. Have you considered giving it a DOI with Zenodo (https://zenodo.org) to make it easier to cite?

**Comment by arnavm** [comment]
Thank you! I hadn't thought about it at the time as I had learned about Zenodo after I posted it. I think it is worth giving it a persistent DOI so people can cite it. Give me a few days and I'll update you with a citation.

**Comment by arnavm** [comment]
Thanks for your patience! I've uploaded this version to Zenodo. Here is the DOI link: https://doi.org/10.5281/zenodo.2628012
